Dk/add restapi pugre
scylladb/scylla-manager pull request #3520
Opened 2023-08-09 23:18 UTC by dkropachev

---

"Only the Best is Good Enough." - LEGO company motto

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

2023-09-14 14:55 UTC, Michal-Leszczynski requested changes
Sorry for large amount of comments, most of them are some nit picks that can probably be ignored. I'm curious why there were so many changes in terms of iterating over value vs index in this PR.

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/service/backup/service.go
> +	runFunc = func(nodeID string, m Manifests) error {
Why not just:
```go
runFunc := func(nodeID string, m Manifests) error {
```
Or do you think that it is more descriptive this way?

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/restapi/backup_test.go
> +	if err != nil {
Maybe combine those two into a single line?

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/restapi/backup_test.go
> +	if err != nil {
Maybe combine those two into a single line?

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/service/backup/list.go
> +		lm, err := listManifests(ctx, client, hosts[idx].IP, hosts[idx].Location, clusterID)
What is the motivation behind this change?

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/service/backup/parallel.go
> +		dc := hosts[idx].DC
What is the motivation behind this change?

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/service/backup/validation.go
> +					return hosts[idx].IP
What is the motivation behind this change?

2023-09-14 14:55 UTC, Michal-Leszczynski commented on pkg/service/backup/worker_schema.go
> +		hostPerLocation = append(hostPerLocation, locations[key])
What is the motivation behind this change?

2023-09-25 10:21 UTC, dkropachev commented
@karol-kokoszka , not yet, I will complete it this week

2024-02-14 21:12 UTC, closed without merging