Use Scylla API for backup
scylladb/scylla-manager pull request #4169
Opened 2024-12-16 11:51 UTC by Michal-Leszczynski

2024-12-18 15:34 UTC, Michal-Leszczynski commented
@karol-kokoszka @VAveryanov8 so the idea is that the `ml/scylla-api` will be the branch for the scylla api milestone.
Please take a look!

2025-01-08 16:08 UTC, VAveryanov8 commented
Nice! Looks good to me! 
Just a few questions/nits

2025-01-08 18:14 UTC, karol-kokoszka reviewed
I will continue with the review, but leaving one comment now. Need to understand why SM must pass s3 endpoint. 
I feel this is the security threat (but maybe I'm wrong, I'm not security expert - convince me that it is not the threat).

2025-01-09 11:18 UTC, Michal-Leszczynski commented on pkg/cmd/agent/router.go
> +	regex := regexp.MustCompile(`^/storage_service/backup$`)
There is none:)
My though process was that in the next PR adding support for restore I would need to also check for the restore endpoint which is `/storage_service/restore` and I just thought that it would be nice to reuse their prefix.
But if you prefer the simpler approach, I can change that (although in general this best effort approach wouldn't probably be released - it's just for the testing now).

2025-01-09 11:21 UTC, Michal-Leszczynski commented on pkg/cmd/agent/router.go
> +
Yeah, that would make sense:)

2025-01-09 11:24 UTC, Michal-Leszczynski commented on pkg/cmd/agent/router.go
> +
done!

2025-01-09 12:12 UTC, karol-kokoszka commented on pkg/cmd/agent/router.go
> +
What happens when there is an error raised in the Directory that is expected to validate&modify the incoming request ? 
I understand that the error is just logged, but proceeds with the call to the scylla server with the current implementation.
This behavior means that the inproper request is proxied still to the scylla server.

It's much more efficient to stop processing the invalid request straight in the proxy instead of forwarding it.
To do that, you can introduce the middleware that is reponsible for validation + 
```
http.Error(w, "Missing required query parameter: endpoint", http.StatusBadRequest)
return
```
The middleware should evaluate the correct endpoint and save it to conext.
Then, the director just checks the context to see if there is something to change.

Director, can skip the validation 
This comment is only valid if you proceed with resolving endpoint in agent. The topic to discuss is that is can be safer/better to have the identifiers of endpoints in object storage and use it in sm configuration.

2025-01-09 12:24 UTC, karol-kokoszka commented on pkg/scyllaclient/client_agent.go
> +
So, it's basing on the release version. 
It's confirmed that Scylla exposes wtih appi beginning with 6.3 and 2024.3 ? 
Is there any other possibility of checking the availablity of this endpoint ? Maybe simple HEAD request to the endpoint ?

2025-01-09 12:38 UTC, karol-kokoszka commented on pkg/service/backup/service.go
> +
Maybe it's safer and more accurate to force config cache to update cluster configuration first ? And then call to Read All.

2025-01-09 12:42 UTC, VAveryanov8 commented on pkg/cmd/agent/router.go
> +	regex := regexp.MustCompile(`^/storage_service/backup$`)
thanks for clarifying, we can leave it for testing :)

2025-01-09 12:43 UTC, Michal-Leszczynski commented on pkg/scyllaclient/client_agent.go
> +
It's not confirmed, we would need  to come back to this part after an actual Scylla release supports native backup/restore API.

2025-01-09 12:44 UTC, karol-kokoszka commented on pkg/service/backup/service_backup_integration_test.go
> +}
`latest-enterprise` has the Scylla API changes included already ? 
I'm asking because I wonder if the GH actions are already testing the scenario with Scylla API for backup.

2025-01-09 12:58 UTC, karol-kokoszka commented on pkg/service/backup/worker_deduplicate.go
> +			willCreateVersioned = true
Why it will create versioned if there is no crc32 file ? We don't know it. It will create versioned only if the checksum generated by Rclone are different.
But there is no option to validate it at this stage, so yeah it's possible better to assume it will.

2025-01-09 13:02 UTC, karol-kokoszka commented on pkg/service/backup/worker_scylla_upload.go
> +		return false, nil
I miss more debug information like why ScyllaBackupAPI is not going to be used.
My proposal is to either replace (bool, error) returns with (error) return, where error!=nil means not supported. Error message can be logged (info) as a reasoning then.
I see you log which API is going to be used, so RClone api log info can be extended with reasoning,.

2025-01-09 13:06 UTC, karol-kokoszka commented on pkg/service/backup/worker_upload.go
> +			return errors.Wrap(err, "check Scylla backup API support")
Why return on error, and not failback to RClone API ?

2025-01-09 13:08 UTC, karol-kokoszka commented on schema/v3.5.0.cql
> +ALTER TABLE backup_run_progress ADD scylla_task_id text;
nit: Why new parameter is needed ? Cannot agent_job_id be used ? (it's not a complain, just the curiosity)

2025-01-09 13:09 UTC, karol-kokoszka commented on v3/swagger/agent.json
> +      }
You have some commits from @VAveryanov8 PR here ?

2025-01-09 13:11 UTC, karol-kokoszka requested changes
@Michal-Leszczynski Thanks for the PR! Looks nice. There are few comments to discuss.
The most important is to figure out what to do with these endpoints configured for object storage.
I'm setting "Request changes" to block it until it's confirmed if core can use IDs for example.

2025-01-09 13:13 UTC, karol-kokoszka commented on pkg/scyllaclient/client_agent.go
> +
Can we assume that if endpoint is available then it means scylla supports it ? If so, then I suggest to probe api with HEAD request.

2025-01-09 14:23 UTC, Michal-Leszczynski commented on pkg/cmd/agent/router.go
> +			resolvedEndpoint = provider
I think that we covered those points during the meeting, right?

2025-01-09 14:35 UTC, Michal-Leszczynski commented on pkg/scyllaclient/client_agent.go
> +
In general I like the idea of not relying on version checks, but proposed approach requires Scylla to handle HEAD requests and I don't think that's the case. At least I can't see them in the swagger definitions or swagger UI.

2025-01-09 14:36 UTC, karol-kokoszka commented on pkg/cmd/agent/router.go
> +			resolvedEndpoint = provider
Right. These are comments from before the sync. Waiting for the output from the meeting then.

2025-01-09 14:36 UTC, Michal-Leszczynski commented on pkg/service/backup/worker_deduplicate.go
> +			willCreateVersioned = true
That's exactly my though process:)

2025-01-09 14:44 UTC, Michal-Leszczynski commented on pkg/service/backup/worker_upload.go
> +			return errors.Wrap(err, "check Scylla backup API support")
We could do it, but do we want to?
Because of https://github.com/scylladb/scylla-manager/issues/4163 it will be possible to control which API should be primarily used for the backup process.
The fallback without any error analysis can prolong the agony of a problematic backup (which might fail with Rclone API as well).
There is also a question of whether interrupting backup with Scylla and resuming it with Rclone is safe (although I don't know why wouldn't it be).

2025-01-09 14:45 UTC, Michal-Leszczynski commented on schema/v3.5.0.cql
> +ALTER TABLE backup_run_progress ADD scylla_task_id text;
They have different types and it also allow for distinguishing which API was used.

2025-01-09 14:52 UTC, Michal-Leszczynski commented on pkg/service/restore/restore_integration_test.go
> -
When using Scylla backup API we don't need to alter transfers, rate limit, cpu pinning etc, so I deleted this check out of laziness. But I can bring it back for testing scenarios using Rclone API.

2025-01-09 15:23 UTC, karol-kokoszka commented on pkg/scyllaclient/client_agent.go
> +
OK, they don't support HEAD requests, at least this is what I see trying to `curl` for it from localhost.
GET responds OK, HEAD gives 404 (not found).

Then maybe, there is some configuration parameter available to GET which can answer whether the feature is available ?

2025-01-09 15:26 UTC, karol-kokoszka commented on pkg/service/backup/worker_upload.go
> +			return errors.Wrap(err, "check Scylla backup API support")
Thanks for the context.
Let's not failback.

2025-01-09 15:26 UTC, karol-kokoszka commented on pkg/service/restore/restore_integration_test.go
> -
yes, please

2025-01-09 15:33 UTC, Michal-Leszczynski commented on pkg/scyllaclient/client_agent.go
> +
Not sure about this suggestion. Wouldn't it be difficult to distinguish potential errors coming from API not being exposed and connectivity issues?
Also, the initial idea was to check Scylla swagger definitions, but it's currently not possible due to https://github.com/scylladb/scylladb/issues/16424.

2025-01-09 15:37 UTC, karol-kokoszka commented on pkg/scyllaclient/client_agent.go
> +
If you have connectivity issue, then you got network level error. You won't get response with HTTP code.

2025-01-10 13:05 UTC, Michal-Leszczynski commented on pkg/scyllaclient/client_agent.go
> +
> Then maybe, there is some configuration parameter available to GET which can answer whether the feature is available ?

Could you elaborate?

2025-01-13 10:14 UTC, karol-kokoszka commented on pkg/scyllaclient/client_agent.go
> +
If core uses some configuration parameter related to the backup API in scylla that is exposed together with this API, there could be simple GET performed on this config param.
404 code means that the API is not available.

But, if the backup API means that there are only POST methods exposed that are changing the state then I think you need to stay with the current approach where you basically checks the versions number.

2025-01-15 10:11 UTC, karol-kokoszka approved these changes

2025-01-15 11:55 UTC, Michal-Leszczynski commented on pkg/service/backup/worker_scylla_upload.go
> +		return false, nil
I don't like mixing actual errors with checks, so I just added logging on failed checks.

2025-01-15 11:58 UTC, merged